// <auto-generated />
namespace HouseMadera.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Modif_Data_Annotation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modif_Data_Annotation));
        
        string IMigrationMetadata.Id
        {
            get { return "201611181018489_Modif_Data_Annotation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
